# Generated by Django 4.0.4 on 2022-06-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseHandler', '0002_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='followcourse',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
