# Generated by Django 4.0.4 on 2022-05-23 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseHandler', '0002_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_course', to='courseHandler.course'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
