# Generated by Django 4.0.4 on 2022-06-09 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courseHandler', '0003_alter_course_is_active_alter_followcourse_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followcourse',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='followcourse',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
