# Generated by Django 4.0.4 on 2022-07-08 08:42

import courseHandler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseHandler', '0008_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='imgs', validators=[courseHandler.models.validate_image]),
        ),
    ]
