# Generated by Django 4.0.4 on 2022-07-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseHandler', '0010_alter_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='followcourse',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
    ]
