# Generated by Django 4.0.4 on 2022-06-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInteractions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='video',
            new_name='videoo',
        ),
    ]
