# Generated by Django 4.0.4 on 2022-06-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInteractions', '0002_rename_video_answer_videoo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='videoo',
            new_name='video',
        ),
    ]
