# Generated by Django 4.0.4 on 2022-07-05 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='image',
            field=models.FileField(default='settings.MEDIA_ROOT/imgs/default.jpg', upload_to='imgs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'svg', 'jpeg'])]),
        ),
    ]
